version: '3'
services:
  frontend-server:
    build: .
    ports:
      # external port: internal port
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./node_modules:/srv/cubee-frontend-server/node_modules
      - ./src:/srv/cubee-frontend-server/src
      - ./config-stg.json:/etc/config.json
    entrypoint: yarn
    command: "start"
