version: '3'
services:
  frontend-server:
    build: .
    ports:
      # external port: internal port
      - "3000:3000"
    volumes:
      - ./config-prod.json:/etc/config.json
    entrypoint: yarn
    command: "start:pm2"
