project:
  name: cubee-frontend-server

image:
  repository: gocreating/cubee-frontend-server
  tag: ${IMAGE_TAG}
  env:
    - name: CUBEE_ENV
      value: "production"

pod:
  labels:
    env: "prod"
    cluster: "cubee-prod"

healthz:
  path: /info
  initialDelay: 300
  period: 600
  timeout: 10
  success: 1
  failure: 3

autoScaling:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

ingress:
  rules:
    - host: cubee.cc
      http:
        paths:
        - path: /
          backend:
            serviceName: cubee-frontend-server
            servicePort: 3000

    - host: "*.cubee.cc"
      http:
        paths:
        - path: /
          backend:
            serviceName: cubee-frontend-server
            servicePort: 3000
