apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.project.name }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - secretName: cubee-cc-tls
      hosts:
        - cubee.cc
        - "*.cubee.cc"
  rules:
{{ toYaml .Values.ingress.rules | indent 4 }}
